stages:
  clean:
    cmd: >
      python scripts/clean.py 
      -i data/raw.csv 
      -o data/clean.csv
    desc: Clean the raw Mauna Loa observatory data for easier use
    deps:
      - scripts/clean.py
      - data/raw.csv
    outs:
      - data/clean.csv
      - plots/mauna_loa.png
  
  split:
    cmd: >
      python scripts/split.py
      -i data/clean.csv
      -o data
      -p params.yaml
    desc: Split the cleaned data at a `split_year` into training & testing data
    params:
      - split_year
    deps:
      - data/clean.csv
    outs:
      - data/train.csv
      - data/test.csv
  
  train:
    cmd: >
      python scripts/train.py
      -i data/train.csv
      -o data
      -p params.yaml
    desc: Compute posterior mean & covariance for weights
    params:
      - scale
      - train.noise_precision
      - train.prior_precision
      - train.cycle_freq
    deps:
      - data/train.csv
    outs:
      - data/post_mean.npy
      - data/post_covmat.npy